type Item = Record<string, any>

export const attractionTypes: Item = {
  "airport-lounge": "Airport Lounge",
  "ancient-ruin": "Ancient Ruin",
  "arena-stad": "Arena & Stadium",
  "beach": "Beach",
  "bridge": "Bridge",
  "canyon": "Canyon",
  "castle": "Castle",
  "cave": "Cave",
  "church": "Church",
  "cemetery": "Cemetery",
  "civic-center": "Civic Center",
  "dam": "Dam",
  "exh": "Exhibition",
  "farm": "Farm",
  "forest": "Forest",
  "historic-site": "Historic Site",
  "island": "Island",
  "market": "Market",
  "mall": "Mall",
  "monument-statue": "Monument & Statue",
  "museum": "Museum",
  "mountain": "Mountain",
  "nat-park": "National Park",
  "park": "Park",
  "playground": "Playground",
  "poi-landmark": "Point of Interest & Landmark",
  "railway": "Railway",
  "temple": "Temple",
  "theater": "Theater",
  "uni-sch": "University & School",
  "vally": "Vally",
  "volcano": "Volcano",
  "waterfall": "Waterfall",
  "zoo": "Zoo",
}