export enum ENDPOINTS {
  GOOGLE_AUTH = "/auth/google",
  EMAIL_SIGNIN_AUTH = "/auth/email/signin",
  EMAIL_SIGNUP_AUTH = "/auth/email/signup",
  GOOGLE_AUTH_CB = "/auth/google/callback",
  USER = "/user",
  TRIP = "/trip",
  PROFILE_TRIP = "/trip/profile-trips",
  DRAWER_TRIP = "/trip/drawer-trips",
  HOME_TRIP = "/trip/home-trips",
  SAVED_TRIP = "/trip/saved",
  INTERACT_TRIP = "/trip/interact",
  LOCATION = "/location",
  LOCATION_SEARCH = "/location/search",
  ITEM = "/item",
  ITEM_SEARCH = "/item/search",
  REVIEW = "/review",
  REVIEW_RATES = "/review/rate",
  UPLOAD = "/upload"
}
