export const enum ROUTES {
  HOME = "/",
  PROFILE = "/profile/:id",
  PROFILE_BASE = "/profile/",
  TRIPS_HOME = "/trips",
  TRIP_BASE = "/trips/",
  TRIP_DETAIL = "/trips/:id",
  TOURISM = "/tourism/:slug",
  TOURISM_BASE = "/tourism/",
  SEARCH = "/search",
  DININGS = "/tourism/:slug/dinings",
  DINING_BASE = "/dining/",
  DINING_DETAIL = "/dining/:id",
  LODGING_BASE = "/lodging/",
  LODGING_DETAIL = "/lodging/:id",
  REVIEW = "/review/:id",
  REVIEW_BASE = "/review/",
  BOOKINGS = "/bookings",
  BOOKING = "/booking/:id",
  BOOKING_BASE = "/booking/",
  SUCCESS = "/success",
  BUSINESS = "/business",
  BUSINESS_BASE = "/business/",
  BUSINESS_DETAIL = "/business/:id",
  NEW_ITEM = "/new-item"
}
